name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build

      - name: Generate changelog (if missing)
        run: |
          if [ ! -f CHANGELOG.md ]; then
            npx standard-version --first-release --skip.tag --skip.commit;
          fi

      - name: Archive production build
        run: |
          tar -czf dist.tar.gz dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: |
            dist.tar.gz
            CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 